2024-Fall-CapstoneDesign/newReals_FE

- src/App.tsx
> #1 [chore] : 실험 중

- eslint.config.js
- package-lock.json
- package.json
- src/App.tsx
- src/AppRouter.tsx
- src/main.tsx
- src/pages/Category.tsx
- src/pages/Home.tsx
- src/pages/Interest.tsx
- src/pages/Intro.tsx
- src/pages/Market.tsx
- src/pages/NewsDetail.tsx
- src/pages/Profile.tsx
> #1 [feat] : router 설정

- src/components/common/footer/Footer.tsx
- src/components/common/footer/FooterStyle.tsx
- src/index.css
- src/main.tsx
#9 
- Footer 구현 및 적용
일단 노션, 인스타그램, 메일 링크 아직 없어서 naver.com로 연결해둠
> [feat] : Footer 구현

- public/icons/OIcon.svg
- public/icons/XIcon.svg
- src/components/common/bookmark/BookmarkStyle.tsx
- src/components/common/button/Button.tsx
- src/components/common/button/ButtonStyle.tsx
- src/components/common/button/PageButtonStyle.tsx
- src/components/common/card/CardStyle.tsx
- src/components/common/chip/ChipStyle.tsx
- src/components/common/footer/FooterStyle.tsx
- src/components/common/quizAnswer/QuizAnswer.tsx
- src/components/common/quizAnswer/QuizAnswerStyle.tsx
- src/components/common/quizAnswer/chip/ChipStyle.tsx
- src/components/common/tag/TagStyle.tsx
- src/components/newsDetail/emojiCount/EmojiCountStyle.tsx
- src/components/newsDetail/quiz/QuizStyle.tsx
#14 
- 1280 사이즈에 맞춰 다시 크기 조정
- 리팩토링 목적 : 노트북으로 봤을 때 전체적으로 큰 느낌이 있음
* 모달 버튼 저렇게 넓은 거 정상임 저거 width 100% 로 해둠 나중에 모달에 적용하면 딱 맞을것임!!
<나중에 참고할 사용 예시>
```
import Button from '../components/common/button/Button';
import PageButton from '../components/common/button/PageButton';
import Card from '../components/common/card/Card';
import Chip from '../components/common/chip/Chip';
import Tag from '../components/common/tag/Tag';
import EmojiCount from '../components/newsDetail/emojiCount/EmojiCount';
import Quiz from '../components/newsDetail/quiz/Quiz';
const Intro = () => {
return (
<div>
인트로 페이지입니다.
<Chip
isSelected={true}
onClick={() => {
console.log('클릭');
}}
>
#키워드
</Chip>
<Tag color="gray" size="large">
정치-행정
</Tag>
<Tag color="purple" size="large">
O/X 퀴즈 …
```
> [refactor] : 1280 사이즈에 맞춰 다시 크기 조정

- src/assets/icons/ModalAction.svg
- src/components/common/coinModal/CoinModal.Style.ts
- src/components/common/coinModal/CoinModal.tsx
#45 
- 코인 획득 모달 완료했습니다. 
- 코인 획득 모달은 이후 출석 팝업 뿐만 아니라 밸런스 게임, 코멘트 달기 등에 사용될 것 같아 확장성을 고려해서 만들었습니다. 
- 애니메이션이 괜찮은지 영상 확인 부탁드립니당. 
- 출석 팝업 연결은 API 나오면 연결하겠습니다 -> 출석 여부를 조회하고 이에 따른 팝업이 나오고 안나오고 해야할 것 같아서 입니다.
> [feat] : 코인 획득 모달 UI 구현

- src/pages/category/Category.tsx
#47 
큰 카테고리 페이지 다음을 리팩토링 했습니다. 
1. 탭바를 선택하고 나서 다시 선택 해제가 안되는 문제를 해결했습니다.
2. 사용하지 않는 카테고리 폴더를 삭제했습니다. 
> [refactor] : 큰 카테고리 페이지 리팩토링

- src/assets/icons/ErrorIcon.svg
- src/assets/icons/InfoIcon.svg
- src/components/profile/profileCard/ProfileCard.Style.ts
- src/components/profile/profileCard/ProfileCard.tsx
- src/components/profile/profileCard/coinExplain/CoinExplain.Style.ts
- src/components/register/errorMessage/ErrorMessage.tsx
#50
- 말풍선 호버 구현 했습니당!
- info 아이콘과 error 아이콘이 달랐다는 점..😆 
> [feat] : 말풍선 호버 구현

- src/components/profile/calendar/Calendar.tsx
> [refactor] : 글씨 추가

- package-lock.json
- package.json
- src/components/newsDetail/aiSummary/AISummary.Style.ts
- src/components/newsDetail/aiSummary/AISummary.tsx
- src/components/newsDetail/easySummary/EasySummary.Style.ts
- src/components/newsDetail/easySummary/EasySummary.tsx
- src/components/newsDetail/easySummary/InfoPart.Style.ts
- src/components/newsDetail/easySummary/InfoPart.tsx
- src/pages/newsDetail/NewsDetail.tsx
- src/styles/Globalstyles.Style.ts
#55
- 쉬운해설 파트 UI 구현
- 용어 클릭 시 해설 뜨는 기능 구현
- 원본 뉴스로 이동
위의 문제는 좀 더 생각해보고 이후에 수정하겠습니다!! ㅜㅜ
> [feat] : 뉴스상세페이지 쉬운해설 파트

- src/components/common/button/Button.Style.ts
- src/components/common/cardList/CardList.tsx
> [refactor] : 버튼 크기 및 뉴스 상세 이동 수정

- .env
- src/components/common/tag/Tag.Style.ts
- src/components/common/tag/Tag.tsx
- src/components/newsDetail/quiz/Quiz.Style.ts
- src/components/newsDetail/quiz/Quiz.tsx
- src/components/newsDetail/thinkingPart/AfterThinking.Style.ts
- src/components/newsDetail/thinkingPart/AfterThinking.tsx
- src/components/newsDetail/thinkingPart/ThinkingPart.Style.ts
- src/components/newsDetail/thinkingPart/ThinkingPart.tsx
- src/pages/newsDetail/NewsDetail.tsx
- 카카오로그인 앱 키.txt
#62
- 생각정리(작성X, 유저수 충분할때, 충분하지 않을때)
- 퀴즈 남은 시간 계산 구현
<생각정리> - 작성X
작성O, 유저수 충분
작성O, 유저수 충분X
<퀴즈 남은 시간 계산>
> [feat] : 생각정리, 퀴즈 남은 시간 계산 구현 (뉴스 상세 페이지)

- src/components/common/button/Button.Style.ts
- src/components/common/button/Button.tsx
- src/components/newsDetail/quiz/Quiz.Style.ts
- src/components/newsDetail/quiz/Quiz.tsx
#68 
공통 버튼 스타일 수정
1. 퀴즈는 퀴즈에서만 사용돼서 퀴즈에서만 사용되도록 분리했습니당! 
2. 공통되는 속성들을 buttonType으로 정리해서 각각의 경우에 해당 스타일이 적용되도록 바꿔보았습니당
> [refactor] : 공통 버튼 스타일 수정

- src/api/Category.ts
- src/components/common/cardList/CardList.tsx
- src/components/common/tabBar/TabBar.tsx
- src/components/home/latestNews/LatestNews.tsx
- src/pages/category/Category.tsx
- src/pages/register/Register.tsx
#89 
1. 큰 카테고리 페이지 API 연동
- 카테고리 조회, 소카테고리 조회 연동 했습니다. 
2. 뉴스 클릭 시  stateData 수정했습니당
> [feat] : 큰 카테고리 페이지 API 연동

- src/api/Profile.ts
- src/components/common/keyword/Keyword.tsx
- src/components/common/keywordList/KeywordList.tsx
- src/components/home/insight/Item.Style.ts
- src/components/profile/activities/Activities.tsx
- src/components/profile/activities/scrap/Scrap.Style.ts
- src/components/profile/activities/scrap/Scrap.tsx
- src/components/profile/editProfile/EditProfile.tsx
- src/components/profile/keywordModal/KeywordModal.tsx
- src/pages/profile/Profile.tsx
#76 
1. 스크랩 뉴스 리스트 조회
2. 스크랩 해제 
3. 프로필 정보 수정 시 닉네임 로컬 스토리지에 다시 저장
4. 관심사 수정
> [feat] : 마이페이지 일부 API 연동 완료

- src/components/home/insight/Item.tsx
- src/components/newsDetail/aiPart/AIPart.tsx
- src/components/newsDetail/aiPart/easySummary/EasySummary.tsx
- src/components/newsDetail/articleHeader/ArticleHeader.tsx
- src/components/newsDetail/emojipart/EmojiPart.tsx
- src/components/newsDetail/quiz/AnswerModal.tsx
- src/components/newsDetail/quiz/Quiz.tsx
- src/components/newsDetail/thinkingPart/AfterThinking.tsx
- src/components/newsDetail/thinkingPart/ThinkingPart.tsx
- src/pages/newsDetail/NewsDetail.tsx
#87 
- 뉴스 조회 (메인, 카테고리, 소카테고리)
- 인사이트 조회 및 등록
- 퀴즈 풀기 및 등록
용어해설, 공감클릭 백에서 수정중입니당
> [api] : 뉴스 상세페이지 api 일부 연동 (공감클릭, 스크랩클릭, 용어 제외)

- src/api/NewsDetail.ts
- src/components/newsDetail/articleHeader/ArticleHeader.tsx
- src/components/newsDetail/quiz/Quiz.tsx
- src/components/newsDetail/thinkingPart/ThinkingPart.tsx
- src/pages/newsDetail/NewsDetail.tsx
#87
- api 파일 분리
- 앞뒤기사 조회 api 연동
> [feat] : 뉴스상세페이지 api 일부 연동 및 api 파일 분리

- src/api/Profile.ts
- src/components/profile/activities/insight/Insight.tsx
- src/components/profile/activities/insight/Item.Style.ts
- src/components/profile/activities/insight/Item.tsx
- src/components/profile/report/Report.tsx
- src/components/profile/report/graph/Chip.Style.ts
- src/components/profile/report/graph/Chip.tsx
- src/components/profile/report/graph/Graph.Style.ts
- src/components/profile/report/graph/Graph.tsx
- src/components/profile/report/interest/Interest.tsx
- src/components/profile/report/keyword/Keyword.tsx
- src/components/profile/report/keyword/KeywordList.tsx
- src/components/profile/report/summary/Summary.tsx
- src/components/profile/report/trend/Item.tsx
- src/components/profile/report/trend/Trend.tsx
- src/components/profile/report/type/Report.ts
#76 
- 마이페이지 분석 레포트 UI 및 API 연동 완료
- UI 디테일 시험 끝나고... 해봅니다 ㅜㅜ 😢
> [feat] : 마이페이지 분석 레포트 UI 및 API 연동 완료

- src/components/newsDetail/articleHeader/ArticleHeader.tsx
#102
- 뉴스 상세 페이지에서 스크랩 버튼 동작 API
> [feat] : 뉴스 상세 페이지에서 스크랩 버튼 동작 API

- src/components/common/header/Header.tsx
> [feat] : 헤더 로그인 연결

- vercel.json
> [fix] : 버셀 배포 수정

- src/styles/Globalstyles.Style.ts
> [fix] : vercel 배포

- vercel.json
> [fix] : vercel 리다이렉트 수정

- src/components/profile/calendar/Calendar.Style.ts
#110 
- 배포 환경에서 출석 아이콘 안보이는 현상 해결
> [fix] : 배포 환경에서 출석 아이콘 안보이는 현상 해결

- index.html
- src/components/common/card/Card.Style.ts
- src/components/common/chip/Chip.Style.ts
- src/components/common/pageNation/PageNation.Style.ts
- src/components/common/pageNation/PageNation.tsx
- src/components/home/insight/Item.Style.ts
- src/components/profile/activities/quiz/Quiz.Style.ts
- src/pages/category/Category.tsx
> [fix] : QA 수정 요구 사항 반영

- src/components/common/button/PageButton.Style.ts
- src/components/common/button/PageButton.tsx
> [fix] : 양옆버튼 수정

- src/api/Search.ts
- src/components/home/insight/Item.tsx
- src/components/home/latestNews/LatestNews.tsx
- src/components/profile/keywordModal/KeywordModal.Style.ts
- src/components/profile/keywordModal/KeywordModal.tsx
- src/pages/category/Category.Style.ts
- src/pages/home/Home.Style.ts
- src/pages/search/Search.Style.ts
- src/pages/search/Search.tsx
#123 
QA 수정 요구 사항 일부 반영
- 인사이트 문구 수정
- 불필요한 콘솔 지우기
- 홈, 큰카테고리, 검색 페이지 양 옆 여백 프로필과 동일하게 수정
- 키워드 편집 모달에서 에러 문구 보이지 않는 것 해결! 
> [refactor] : QA 수정 요구 사항 일부 반영 

- src/api/Login.ts
- src/api/instance.ts
- src/components/intro/kakaoLogin/RedirectPage.tsx
- src/components/profile/activities/insight/Insight.tsx
> [fix] : 마이페이지 QA 수정 사항 반영

- src/components/profile/report/graph/Chip.tsx
> [refactor] : 글씨 수정

- src/components/common/card/Card.Style.ts
- src/components/common/cardList/CardList.Style.ts
- src/components/common/coinModal/CoinModal.Style.ts
- src/components/common/footer/Footer.Style.ts
- src/components/common/footer/Footer.tsx
- src/components/common/headNews/HeadNews.Style.ts
- src/components/common/pageNation/PageNation.Style.ts
- src/components/common/pageNation/PageNation.tsx
- src/components/common/tag/Tag.Style.ts
- src/components/home/insight/Insight.Style.ts
- src/components/home/insight/Item.Style.ts
- src/components/home/latestNews/LatestNews.Style.tsx
- src/pages/home/Home.Style.ts
#139 
- 홈페이지 반응형 UI 구현 완료
- 헤더는 우리 누가 할까용...? 
키워드 가로 스크롤 안했다... 하고 머지합니당
> [feat] : 홈 페이지 반응형 UI 구현

- README.md
- src/components/common/card/Card.Style.ts
- src/components/common/headNews/HeadNews.Style.ts
- src/components/common/header/Header.Style.ts
- src/components/common/tabBar/TabBar.Style.ts
- src/pages/category/Category.Style.ts
#129, #142
큰 카테고리 페이지 반응형 UI 구현
> [feat] : 큰 카테고리 페이지 반응형 UI 구현

- src/components/common/header/Header.Style.ts
- src/components/common/header/Header.tsx
- src/components/intro/intro1/Intro_1.Style.ts
- src/components/intro/intro2/Intro_2.Style.ts
- src/components/intro/intro2/Intro_2.tsx
- src/components/intro/kakaoLogin/KakaoLogin.Style.ts
- src/components/intro/layout/CommonLayout.Style.ts
- src/components/intro/layout/IntroContent.Style.ts
인트로 페이지 반응형 UI 구현
인트로 페이지 반응형 UI 구현
이 두번째 슬라이드가 왜 중간정렬이 안될까요..?
얘는 도대체 왜 겹쳐있는걸까요 ㅠㅠㅠㅜ
저것들이 너무 해결이 안됩니다... 한번 봐주신다면 감사하겠습니당..! 글고 이미지 다 빼보니까 너무 밋밋한데 어떻게 할까요,, 넣으면 난리납니다 또...
> [feat] : 인트로 페이지 반응형 UI 구현

- src/components/intro/intro2/Intro_2.Style.ts
- src/components/intro/layout/CommonLayout.Style.ts
- src/components/intro/layout/CommonLayout.tsx
> [fix] : 중앙 정렬 해결

- src/components/market/ItemList.Style.ts
- src/pages/market/Market.Style.ts
- src/pages/market/Market.tsx
> [feat] : 마켓 페이지 반응형 UI 구현
